FROM node:14

EXPOSE 80

# Create server directory
RUN mkdir -p /usr/src/server
WORKDIR /usr/src/server
# Installing dependencies
COPY ./package*.json /usr/src/server/

RUN npm install -g pm2 &&\
    npm install --no-progress --ignore-optional

# Copying source files
COPY . /usr/src/server

# Running the app
CMD "npm" "run" "start:server"
