services:
  server:
    build: 
      context: .
      dockerfile: ./Dockerfile.server
    env_file:
      - .server.env
    ports:
      - 80:80
    volumes:
      - ./:/usr/src/server/
      - /usr/src/server/node_modules
  server_dev:
    build:
      context: .
      dockerfile: ./Dockerfile.server
    depends_on:
      - mongo
    ports:
      - 3101:80
    volumes:
      - ./:/usr/src/server/
      - /usr/src/server/node_modules
  mongo:
    image: mongo
    volumes:
      - "db-data:/data/db"
    environment:
      MONGO_INITDB_DATABASE: db
  www:
    build:
      context: .
      dockerfile: ./Dockerfile.www
    command: npm run start:www
    env_file:
      - .www.env
    ports:
      - 80:80
    volumes:
      - ./:/usr/src/www/
      - /usr/src/www/node_modules
      - /usr/src/www/.next
  www_dev:
    build:
      context: .
      dockerfile: ./Dockerfile.www
    depends_on:
      - mongo
      - mongoku
    command: npm run start:www_dev
    ports:
      - 3100:3100
    volumes:
      - ./:/usr/src/www/
      - /usr/src/www/node_modules
      - /usr/src/www/.next
  mongoku:
    image: huggingface/mongoku
    depends_on:
      - mongo
    ports:
      - 3200:3100
    environment:
      MONGOKU_DEFAULT_HOST: mongo

volumes:
  db-data:
