" CTRL-H to flip hebrew<->english
function Rightleft_flip()
  if &rightleft
    :set norightleft
  else
    :set rightleft
  endif
endfunction
map <C-h> :call Rightleft_flip()<CR>

au BufNewFile,BufRead *.json6 setlocal filetype=javascript

